# Generated by Django 6.0.1 on 2026-01-20 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='short_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='country',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CountryRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='countries.country')),
            ],
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
