# Generated by Django 6.0.1 on 2026-02-05 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_country_short_description_alter_country_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='countries.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaCRSFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('points', models.CharField(max_length=50)),
                ('factors', models.TextField(help_text='Comma-separated list of factors')),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crs_factors', to='countries.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaEligibilityRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_requirements', to='countries.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='countries.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaProcessingTimeAndFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_time_and_fees', to='countries.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('visa_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='countries.visatype')),
            ],
        ),
        migrations.CreateModel(
            name='VisaProgramOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_heading', models.CharField(max_length=200)),
                ('points', models.TextField()),
                ('last_paragraph', models.TextField()),
                ('visa_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_overview', to='countries.visatype')),
            ],
        ),
    ]
