# Generated by Django 6.0.1 on 2026-02-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_visabenefit_visacrsfactor_visaeligibilityrequirement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visaprogramoverview',
            name='points',
        ),
        migrations.CreateModel(
            name='VisaProgramOverviewPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('program_overview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='countries.visaprogramoverview')),
            ],
        ),
    ]
