# Generated by Django 6.0.1 on 2026-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_remove_visaprogramoverview_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='full_name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visabenefit',
            name='icon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visabenefit',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visacrsfactor',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visacrsfactor',
            name='points',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaeligibilityrequirement',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visafee',
            name='cost',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visafee',
            name='item',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaprocessingtimeandfee',
            name='header',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaprocessingtimeandfee',
            name='icon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaprocessingtimeandfee',
            name='time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaprocessstep',
            name='duration',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visaprocessstep',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaprogramoverview',
            name='first_heading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaprogramoverviewpoint',
            name='icon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visaprogramoverviewpoint',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='processing_time',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visatype',
            name='validity_period',
            field=models.TextField(),
        ),
    ]
