# Generated by Django 6.0.1 on 2026-02-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resourcetip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resource',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resourcesection',
            name='heading',
            field=models.TextField(),
        ),
    ]
